# Generated by Django 4.0.4 on 2022-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_date_post_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
